engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    count_threshold: 3
    config:
      languages:
        javascript:
          count_threshold: 3
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
