engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
     - a5b7773894f9d89e6dfe6b4408b3099c
    config:
      languages:
        javascript:
          count_threshold: 3
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
